"""hashed_password

Revision ID: 9ce03f30aa1f
Revises: de969a104090
Create Date: 2025-11-06 16:18:19.169326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce03f30aa1f'
down_revision: Union[str, Sequence[str], None] = 'de969a104090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_column('usermodel', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('usermodel', 'hashed_password')
    # ### end Alembic commands ###
